Testframework running - testcases fail due to loading of tracker asset
System.IO.FileNotFoundException: Could not load file or assembly
'TrackerAsset, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or